# Site
repository: MariagiovannaRotundo/resume
favicon: images/kiwi.ico

# Content configuration version
version: 2

# Personal info
name: Mariagiovanna Rotundo
title: Ph.D. student 
email: mariagiovannarotundo@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  MariagiovannaRotundo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: Mariagiovanna Rotundo
# flickr_username: jekyll
instagram_username: yz.mary
linkedin_username: mariagiovanna-rotundo
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0009−0001−1671−7407

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_photo.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi! my name is Mariagiovanna Rotundo and I'm a Ph.D. student in computer science at the University of Pisa. I'm currently working on topic of succinct data structures and, with my supervisors, I've published my first scientific paper. In my spare time, I'm an active member of the two local communities GDG and WTM Pisa, which organize free talks about different topics and technologies in the field of computer science.
  
  I am most skilled in: <mark>Java</mark>, <mark>Problem solving</mark>, and <mark>Organization</mark> 

#and <mark>Cuddle cats</mark>
content:
  
  - title: Professional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ph.D. student
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: University of Pisa
        caption: Nov 2023 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            I'm a Ph.D. student :D

      - layout: left
        title: Research Fellow
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: University of Pisa
        caption: Jan 2023 - Nov 2023
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Working on the topic "Compressed data structures to index datasets of keys with variable length".
            We study the problem of engineering space-time efficient indexes that support membership and lexicographic queries on very large static dictionaries of strings.
            The solution we propose is based on a very simple approach that consists of decoupling string storage and string indexing. Supervisors: Paolo Ferragina, Giorgio Vinciguerra. 





  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Master's degree in Computer Science
        caption: 2020 - 2022
        sub_title: University of Pisa
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I've attended the curriculum "ICT Solutions Architect" where, among all the topics, I've studied how to design heterogeneous and distributed software systems and how to well parallelize software.
          I graduated with the grade of 110/110 cum laude with a thesis where we've proposed a solution for compressed string dictionaries via Rear coding and succinct Patricia Tries. My supervisors were Paolo Ferragina and Giorgio Vinciguerra.
      
      - layout: left
        title: Bachelor's degree in Computer Science
        caption: 2017 - 2020
        sub_title: University of Pisa
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I've learn the basis about different topics in IT. I've graduated with the grade of 110/110 cum laude with a thesis where we've proposed a python package for the batch simulation of chemical reaction networks. My supervisors were Paolo Milazzo and Lucia Nasti.


  - title: Publications # Title for the section
    layout: text # Type of content section (list/text)
    content: | 
      - **Two-level massive string dictionaries**, *P. Ferragina, M. Rotundo, G. Vinciguerra*  
      Information Systems, 2024. DOI: [10.1016/j.is.2024.102490](https://doi.org/10.1016/j.is.2024.102490)

      
      - **Engineering a textbook approach to index massive string dictionaries**, *P. Ferragina, M. Rotundo, G. Vinciguerra*  
      30th International Symposium String Processing and Information Retrieval (SPIRE), 2023. DOI: [10.1007/978-3-031-43980-3\_16](https://doi.org/10.1007/978-3-031-43980-3_16)
  


  - title: Talks # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: SPIRE
        caption: September 2023
        # sub_title: conference
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **Engineering a textbook approach to index massive string dictionaries**   
          Talk held at the 30th International Symposium String Processing and Information Retrieval. Talk's topic: description of the scientific results published in SPIRE 2023, concerning an approach to index massive string dictionaries.
      - layout: left
        title: GDG Pisa
        caption: November 2022
        # sub_title: GDG Pisa
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **How do I hack your contactless**  
          Topic: how the protocol used by the contactless payments cards works and discussion of [Card Brand Mixup Attack](https://www.usenix.org/system/files/sec21-basin.pdf)

  - title: Publications # Title for the section
    layout: text # Type of content section (list/text)
    content: | 
      - **Two-level indexing**, [<i class="fab fa-github"></i>](https://github.com/MariagiovannaRotundo/Two-level-indexing)  
      Master's degree project extended to implement the data structures and algorithms published in SPIRE 2023. Used programming language: <mark>C++</mark>  

      
      - **Parallel BFS**, [<i class="fab fa-github"></i>](https://github.com/MariagiovannaRotundo/SPM)  
      University project for Parallel and Distributed System course.
      Implementation and performance comparison of a parallel Breadth-first search (BFS) using the standard thread library and FastFlow. Used programming language: <mark>C++</mark>   


      - **SBML-batch**, [<i class="fab fa-github"></i>](https://github.com/MariagiovannaRotundo/SBML-batch)  
      Bachelor's project to analyze collections of chemical reaction networks. 
      Our goal was to (i) provide an implementation of 2 Theorems that under some conditions can give us information on how the networks behave, 
      (ii) create a package to simulate in batch a lot of chemical reaction networks, (iii) provide an implementation to automathically build the Petri Nets of the chemical reaction networks. Used programming language: <mark>Python</mark>  


      - **WordQuizzle**, [<i class="fab fa-github"></i>](https://github.com/MariagiovannaRotundo/WordQuizzle)  
      University project for computer networks course. Implementation of a challenge system between registered users and management of networks of users. Used programming language: <mark>Java</mark>  



  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Two-level indexing
  #       # link: link title
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  MariagiovannaRotundo/Two-level-indexing
  #           icon: fab fa-github
  #           url: github.com/MariagiovannaRotundo/Two-level-indexing
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       description: | # this will include new lines to allow paragraphs
  #         Master's degree project extended to implement the data structures and algorithms published in SPIRE 2023. Used programming language: C++



  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
